// Builds a single self-contained HTML file (hemingway.html) with the CSS and
// every JS module inlined, so it can be opened straight from the filesystem by
// double-clicking it — no server, no network.
//
// The multi-file index.html can't do that: browsers block `<script type="module"
// src="...">` over file:// as a cross-origin request. An *inline* module script
// has no such fetch, so bundling everything into one <script> sidesteps it.
//
// Run with: npm run build

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));

// Modules in dependency order; each only depends on ones before it.
const MODULE_FILES = ["js/wordLists.js", "js/analyze.js", "js/render.js", "js/app.js"];

const IMPORT_RE = /^import\s+[\s\S]*?from\s+["'][^"']+["'];?[ \t]*$/gm;
const EXPORT_RE = /^export\s+(?=const |let |function |class )/gm;

// Appended to the bundle so the build can prove the inline script wasn't cut
// short; if this marker is missing from the emitted tag, the bundle truncated.
const BUNDLE_END_MARKER = "/* bundle:end */";

// Strips the ES module boundary syntax. Safe here because every module is
// first-party and only uses static top-level imports/exports; the bundle keeps
// them all in one scope, so the bindings resolve by plain lexical scoping.
function stripModuleSyntax(source) {
  return source.replace(IMPORT_RE, "").replace(EXPORT_RE, "");
}

// An HTML parser ends a <script> block at the first "</script>" it sees, even
// inside a JS comment or string literal — and the sources legitimately contain
// that text when discussing escaping. Breaking it as "<\/script" is inert in
// JS (in a string "\/" is just "/", in a regex it's an escaped slash, in a
// comment it's only text) but no longer closes the tag.
function neutralizeClosingTags(source) {
  return source.replace(/<\/(script)/gi, (_, tag) => `<\\/${tag}`);
}

function bundleScripts() {
  const bundled = MODULE_FILES.map(file => {
    const source = readFileSync(join(root, file), "utf8");
    return `// ===== ${file} =====\n${neutralizeClosingTags(stripModuleSyntax(source).trim())}`;
  }).join("\n\n");
  return `${bundled}\n${BUNDLE_END_MARKER}`;
}

function build() {
  const html = readFileSync(join(root, "index.html"), "utf8");
  const css = readFileSync(join(root, "css/styles.css"), "utf8");
  const scripts = bundleScripts();

  // Replacer *functions*, not strings: the inlined sources contain "$&"
  // (e.g. the "\\$&" in escapeRegExp), which String.replace would otherwise
  // expand as a substitution pattern and corrupt the bundle.
  let out = html.replace(
    /[ \t]*<link rel="stylesheet" href="css\/styles\.css">\n?/,
    () => `  <style>\n${css.trim()}\n  </style>\n`
  );

  out = out.replace(
    /[ \t]*<script type="module" src="js\/app\.js"><\/script>\n?/,
    () => `  <script type="module">\n${scripts}\n  </script>\n`
  );

  // Fail loudly rather than silently shipping a broken file. These checks
  // exist because both failures are silent in a browser: a dead reference
  // just doesn't load, and a stray "</script>" truncates the bundle mid-file
  // without raising an error.
  const deadReference = /(?:href|src)=["'](?:css|js)\//.exec(out);
  if (deadReference) {
    throw new Error(`build failed: external reference remains: ${deadReference[0]}`);
  }

  const inlineModule = /<script type="module">([\s\S]*?)<\/script>/.exec(out);
  if (!inlineModule) {
    throw new Error("build failed: inline module script missing from output");
  }
  if (!inlineModule[1].includes(BUNDLE_END_MARKER)) {
    throw new Error(
      "build failed: inline module truncated — a stray '</script>' closed the tag early"
    );
  }

  const banner =
    "<!-- Generated by build.js from index.html, css/, and js/ — edit those, not this file. -->\n";
  writeFileSync(join(root, "hemingway.html"), banner + out);

  const kb = (Buffer.byteLength(banner + out) / 1024).toFixed(1);
  console.log(`Wrote hemingway.html (${kb} KB)`);
}

build();
