plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.hemingway.withoutai"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.hemingway.withoutai"
        // API 23 is where the PROCESS_TEXT selection toolbar arrived.
        minSdk = 23
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    // The engine asset is generated, not committed here — see copyEngine below.
    sourceSets["main"].assets.srcDir(layout.buildDirectory.dir("generated/assets"))
}

/**
 * Copies the single-file build from the repository root into the APK's assets.
 *
 * Deliberately a copy of the canonical artifact rather than a second checked-in
 * file: `hemingway.html` is generated by `npm run build` and CI already fails if
 * the committed copy is stale, so the phone cannot drift from the website.
 */
val copyEngine by tasks.registering(Copy::class) {
    val engine = rootProject.file("../hemingway.html")
    from(engine)
    into(layout.buildDirectory.dir("generated/assets"))

    doFirst {
        require(engine.exists()) {
            "hemingway.html not found at ${engine.path}. Run `npm run build` in the " +
                "repository root first — the APK embeds that file as its engine."
        }
    }
}

tasks.named("preBuild") { dependsOn(copyEngine) }
